baseURL = 'https://sebastianemery.com/'
languageCode = 'en-us'
title = 'Sebastian Emery'
theme = 'nyara'
SectionPagesMenu = "main"
enableRobotsTXT = true
[services]
[services.disqus]
shortname = 'sebastianemery-com'
[sitemap]
 chagefreq = "weekly"
 filename = "sitemap.xml"
 priority = 0.5

[params.ananke.social.follow]
new_window_icon = false
networks = [
    "youtube",
    "bluesky"
]

[params.ananke.social.youtube]
username = "sebastian-emery-author"

[params.ananke.social.bluesky]
username = "sebastianemery.com"
profilelink = "https://bsky.app/profile/sebastianemery.com"

[markup.goldmark.renderer]
unsafe = true